### ISSUE TITLE
dockerOptions is deprecated show even when not set on the Soda Scan and various Dbt tasks

### ISSUE THREAD

**Issue by Skraye** [kestra-io/plugin-soda#29]
### Explain the bug

I guess this is due to settings it by default with the new docker props for retro compatibility
We need to find a better way, or at least a way not to show the deprecated warning when not used

![image](https://github.com/kestra-io/kestra/assets/37600690/99fe6ebd-75e7-456d-88a9-f73fd52a03ad)

### Environment Information

- Kestra Version: 0.12.0
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by anna-geller** [comment]
edit: the same happens on dbt Test task (likely all dbt tasks which are not Dbt CLI)

![image](https://github.com/kestra-io/plugin-soda/assets/86264395/48270478-2856-4a39-8105-2f2fc84f8072)
